name: "My JavaScript Action"
description: "A simple GitHub Action written in JavaScript"
inputs:
 name:
   description: "Name to greet"
   required: true
   default: "World"
outputs:
 time:
   description: "The time the greeting occurred"
runs:
 using: "node20"
 main: "dist/index.js"