name: "process-service-repo-dispatch"
description: "Process OnFusionCoe service repo dispatch operation"

on:
  workflow_call:
    inputs:
      client_id:
        description: "The application id to authenticate with."
        required: true

      tenant_id:
        description: "Tenant id if using app-id & client secret to authenticate."
        required: true

      cloud:
        description: 'Cloud instance to authenticate with. Default: Public. See "pac auth create help" for valid cloud instance names'
        required: false
        default: 'Public'

      authority:
        description: 'Microsoft authentication authority for the target cloud.'
        required: false
        default: 'https://login.microsoftonline.com/'

      # secrets:

      client_secret:
        description: "The client secret to authenticate with. Required if authenticating with app-id."
        required: true

runs:
  using: "composite"
  steps:
    - name: authentication
      shell: pwsh
      run: |
        echo "Handling dispatch operation ${{github.event.action}}"
        # get-content ${{ github.event_path }} 

        $TenantId = "${{ inputs.tenant_id }}"
        $AppClientId="${{ inputs.client_id }}"        
        $ClientSecret ="${{ inputs.client_secret }}"
        $Authority ="${{ inputs.authority }}"

        $InvokeUrl = "$Authority$TenantId/oauth2/v2.0/token"
          
        $RequestBody = @{client_id=$AppClientId;client_secret=$ClientSecret;grant_type="client_credentials";scope="https://graph.microsoft.com/.default";}

        echo $InvokeUrl
        echo $RequestBody

        $OAuthResponse = Invoke-RestMethod -Method Post -Uri $InvokeUrl -Body $RequestBody
        $AccessToken = $OAuthResponse.access_token

        $AuthorizationHeader = "bearer $AccessToken"

        echo $AuthorizationHeader

    - name: Checking Credentials
      shell: pwsh
      run: |
        echo "V1 Checking for bearer token: ${{env.SPN_BEARER}}"
        echo "V2 Checking for bearer token: $SPN_BEARER"

    - name: Checking Credentials v2
      shell: pwsh
      run: |
        echo "V2 Checking for bearer token: $env:SPN_BEARER"
